db_path: "C:/Users/Administrator/OneDrive/Database/multi_period_channel_summary.db"
sales_data_path: "C:/Users/Administrator/Desktop/多时段详细渠道查询.csv"
supplemental_data_path : "C:/Users/Administrator/Desktop/销售数据补录查询.csv"